package main

import (
	"bytes"
	"compress/gzip"
	"encoding/binary"
	"fmt"
	"io"

	_ "embed"

	"github.com/oisee/open-diag-go-pro/pkg/replay"
)

// show.bin is the self-contained show asset: the four wrapper DIAG frames the
// light-show needs (counter, logon, list-wrapper, popup), SCRUBBED of every
// identifier, stored UNCOMPRESSED inside a gzip blob. Generated by scratch_gen.go
// from a capture and committed identifier-free (see the scrub/verify there).
//
//go:embed show.bin
var showBin []byte

// asset is the decoded show: a synthetic capture holding the two dynpro wrapper
// frames (so findCounterFrames / loadLogonWrap locate them by content, exactly
// as the demo mode does), plus the raw list-wrapper and popup bytes.
type asset struct {
	cap      *replay.Capture
	listWrap []byte
	popup    []byte
}

// loadAsset decompresses the embedded blob and builds the synthetic capture.
func loadAsset() (*asset, error) {
	zr, err := gzip.NewReader(bytes.NewReader(showBin))
	if err != nil {
		return nil, fmt.Errorf("gzip: %w", err)
	}
	b, err := io.ReadAll(zr)
	if err != nil {
		return nil, fmt.Errorf("inflate: %w", err)
	}
	r := bytes.NewReader(b)
	var n uint32
	if err := binary.Read(r, binary.BigEndian, &n); err != nil {
		return nil, err
	}
	frames := make([][]byte, n)
	for i := range frames {
		var l uint32
		if err := binary.Read(r, binary.BigEndian, &l); err != nil {
			return nil, err
		}
		fr := make([]byte, l)
		if _, err := io.ReadFull(r, fr); err != nil {
			return nil, err
		}
		if l > 0 {
			frames[i] = fr
		}
	}
	// Order written by the generator: counter, logon, listwrap, popup.
	if len(frames) < 4 {
		return nil, fmt.Errorf("show asset: want 4 sections, got %d", len(frames))
	}
	a := &asset{
		cap: &replay.Capture{Server: []replay.Frame{
			{Index: 0, Data: frames[0]}, // counter (GV_TICKS)
			{Index: 1, Data: frames[1]}, // logon (RSYST-MANDT)
		}},
		listWrap: frames[2],
		popup:    frames[3],
	}
	return a, nil
}
